### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by portu-sim** [Comfy-Org/registry-web#11]
I can't log in.

Click Login

<img width="454" alt="image" src="https://github.com/Comfy-Org/registry-web/assets/141602933/b8d15347-7641-4079-8414-5ddcff20ef2a">

"Sign In" ??
<img width="509" alt="image" src="https://github.com/Comfy-Org/registry-web/assets/141602933/e3b15bbc-629f-4d6e-b4ca-2cfe24019890">

Error

<img width="352" alt="image" src="https://github.com/Comfy-Org/registry-web/assets/141602933/a62e8762-8c33-477b-b739-bd30b15887c4">

AND 

Please READ email from portu-sim.
I have an other issue.

**Comment by yoland68** [comment]
It shows you logged in as a google account, are you using your github account to log in?

**Comment by robinjhuang** [comment]
Please log in using your original account for now (Google Sign In). We will implement account linking soon so you can log in with either account. 

We use firebase login and it blocks accounts that have the same email. Guessing your github and google sign in uses the same email?

**Comment by portu-sim** [comment]
Github and Google use the same email. Both result in the same error. Is this a problem with the certification process? It doesn't seem to be an error in the code. Can I just wait until it expires?

**Comment by robinjhuang** [comment]
@portu-sim Is this error still happening?

**Comment by robinjhuang** [comment]
@portu-sim Looks like your node belongs to your Google email account. Can you try signing in with Google?

**Comment by portu-sim** [comment]
@robinjhuang  You're right. Thank you for your grate support!!!
All issue cleared.
