### ISSUE TITLE
Attempts to register hard-fail with "Too much recursion" in embedded Javascript

### ISSUE THREAD

**Issue by teward** [Comfy-Org/registry-web#9]
Currently, it is not possible to register on comfyregistry.org in order to add a new publisher ID.  This is because of the system returning a hard recursion failure.

```text
Uncaught InternalError: too much recursion
    NextJS 9
        track
        track
        track
        track
        track
        track
        track
        track
        track
```

Above is the output from the console logs on Firefox.  This is duplicated in multiple browsers on multiple OSes.

**Comment by robinjhuang** [comment]
Fixed by reverting https://github.com/Comfy-Org/registry-web/commit/d4de67030379ae21f56d604c7fd622d46228f771. Thanks for reporting it!
